EC2:
  - 'CPUUtilization'
  - 'DiskReadOps'
  - 'DiskWriteOps'
  - 'DiskReadBytes'
  - 'DiskWriteBytes'
  - 'NetworkIn'
  - 'NetworkOut'
RDS:
  - 'BinLogDiskUsage'
  - 'CPUUtilization'
  - 'DatabaseConnections'
  - 'DiskQueueDepth'
  - 'FreeableMemory'
  - 'FreeStorageSpace'
  - 'ReplicaLag'
  - 'SwapUsage'
  - 'ReadIOPS'
  - 'WriteIOPS'
  - 'ReadLatency'
  - 'WriteLatency'
  - 'ReadThroughput'
  - 'WriteThroughput'
  - 'NetworkReceiveThroughput'
  - 'NetworkTransmitThroughput'
